/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pmem_kvdk_Engine */

#ifndef _Included_io_pmem_kvdk_Engine
#define _Included_io_pmem_kvdk_Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pmem_kvdk_Engine
 * Method:    closeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pmem_kvdk_Engine_closeInternal(JNIEnv*, jobject,
                                                              jlong);

/*
 * Class:     io_pmem_kvdk_Engine
 * Method:    open
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_io_pmem_kvdk_Engine_open(JNIEnv*, jclass, jstring,
                                                      jlong);

/*
 * Class:     io_pmem_kvdk_Engine
 * Method:    put
 * Signature: (J[BII[BIIJZ)V
 */
JNIEXPORT void JNICALL Java_io_pmem_kvdk_Engine_put(JNIEnv*, jobject, jlong,
                                                    jbyteArray, jint, jint,
                                                    jbyteArray, jint, jint,
                                                    jlong, jboolean);

/*
 * Class:     io_pmem_kvdk_Engine
 * Method:    expire
 * Signature: (J[BIIJ)V
 */
JNIEXPORT void JNICALL Java_io_pmem_kvdk_Engine_expire__J_3BIIJ(
    JNIEnv*, jobject, jlong, jbyteArray, jint, jint, jlong);

/*
 * Class:     io_pmem_kvdk_Engine
 * Method:    expire
 * Signature: (JJIJ)V
 */
JNIEXPORT void JNICALL Java_io_pmem_kvdk_Engine_expire__JJIJ(JNIEnv*, jobject,
                                                             jlong, jlong, jint,
                                                             jlong);

/*
 * Class:     io_pmem_kvdk_Engine
 * Method:    get
 * Signature: (J[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_pmem_kvdk_Engine_get(JNIEnv*, jobject,
                                                          jlong, jbyteArray,
                                                          jint, jint);

/*
 * Class:     io_pmem_kvdk_Engine
 * Method:    delete
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_io_pmem_kvdk_Engine_delete(JNIEnv*, jobject, jlong,
                                                       jbyteArray, jint, jint);

/*
 * Class:     io_pmem_kvdk_Engine
 * Method:    sortedCreate
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_io_pmem_kvdk_Engine_sortedCreate(JNIEnv*, jobject,
                                                             jlong, jlong,
                                                             jint);

/*
 * Class:     io_pmem_kvdk_Engine
 * Method:    sortedDestroy
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_io_pmem_kvdk_Engine_sortedDestroy(JNIEnv*, jobject,
                                                              jlong, jlong,
                                                              jint);

/*
 * Class:     io_pmem_kvdk_Engine
 * Method:    sortedSize
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_io_pmem_kvdk_Engine_sortedSize(JNIEnv*, jobject,
                                                            jlong, jlong, jint);

/*
 * Class:     io_pmem_kvdk_Engine
 * Method:    sortedPut
 * Signature: (JJI[BII[BII)V
 */
JNIEXPORT void JNICALL Java_io_pmem_kvdk_Engine_sortedPut(JNIEnv*, jobject,
                                                          jlong, jlong, jint,
                                                          jbyteArray, jint,
                                                          jint, jbyteArray,
                                                          jint, jint);

/*
 * Class:     io_pmem_kvdk_Engine
 * Method:    sortedGet
 * Signature: (JJI[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_pmem_kvdk_Engine_sortedGet(
    JNIEnv*, jobject, jlong, jlong, jint, jbyteArray, jint, jint);

/*
 * Class:     io_pmem_kvdk_Engine
 * Method:    sortedDelete
 * Signature: (JJI[BII)V
 */
JNIEXPORT void JNICALL Java_io_pmem_kvdk_Engine_sortedDelete(JNIEnv*, jobject,
                                                             jlong, jlong, jint,
                                                             jbyteArray, jint,
                                                             jint);

/*
 * Class:     io_pmem_kvdk_Engine
 * Method:    sortedIteratorCreate
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_io_pmem_kvdk_Engine_sortedIteratorCreate(
    JNIEnv*, jobject, jlong, jlong, jint);

/*
 * Class:     io_pmem_kvdk_Engine
 * Method:    writeBatchCreate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_pmem_kvdk_Engine_writeBatchCreate(JNIEnv*,
                                                                  jobject,
                                                                  jlong);

/*
 * Class:     io_pmem_kvdk_Engine
 * Method:    batchWrite
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_pmem_kvdk_Engine_batchWrite(JNIEnv*, jobject,
                                                           jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
