/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pmem_kvdk_NativeBytesHandle */

#ifndef _Included_io_pmem_kvdk_NativeBytesHandle
#define _Included_io_pmem_kvdk_NativeBytesHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pmem_kvdk_NativeBytesHandle
 * Method:    newNativeBytes
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL
Java_io_pmem_kvdk_NativeBytesHandle_newNativeBytes(JNIEnv*, jclass, jbyteArray);

/*
 * Class:     io_pmem_kvdk_NativeBytesHandle
 * Method:    closeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_io_pmem_kvdk_NativeBytesHandle_closeInternal(JNIEnv*, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
