/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pmem_kvdk_Iterator */

#ifndef _Included_io_pmem_kvdk_Iterator
#define _Included_io_pmem_kvdk_Iterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pmem_kvdk_Iterator
 * Method:    closeInternal
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_pmem_kvdk_Iterator_closeInternal(JNIEnv*,
                                                                jobject, jlong,
                                                                jlong);

/*
 * Class:     io_pmem_kvdk_Iterator
 * Method:    seek
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_io_pmem_kvdk_Iterator_seek(JNIEnv*, jobject, jlong,
                                                       jbyteArray, jint, jint);

/*
 * Class:     io_pmem_kvdk_Iterator
 * Method:    seekToFirst
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pmem_kvdk_Iterator_seekToFirst(JNIEnv*, jobject,
                                                              jlong);

/*
 * Class:     io_pmem_kvdk_Iterator
 * Method:    seekToLast
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pmem_kvdk_Iterator_seekToLast(JNIEnv*, jobject,
                                                             jlong);

/*
 * Class:     io_pmem_kvdk_Iterator
 * Method:    isValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_pmem_kvdk_Iterator_isValid(JNIEnv*, jobject,
                                                              jlong);

/*
 * Class:     io_pmem_kvdk_Iterator
 * Method:    next
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pmem_kvdk_Iterator_next(JNIEnv*, jobject, jlong);

/*
 * Class:     io_pmem_kvdk_Iterator
 * Method:    prev
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pmem_kvdk_Iterator_prev(JNIEnv*, jobject, jlong);

/*
 * Class:     io_pmem_kvdk_Iterator
 * Method:    key
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_pmem_kvdk_Iterator_key(JNIEnv*, jobject,
                                                            jlong);

/*
 * Class:     io_pmem_kvdk_Iterator
 * Method:    value
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_pmem_kvdk_Iterator_value(JNIEnv*, jobject,
                                                              jlong);

#ifdef __cplusplus
}
#endif
#endif
